# Generated by Django 3.2.7 on 2021-10-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=500)),
                ('city', models.CharField(blank=True, max_length=500)),
                ('division', models.CharField(blank=True, max_length=500)),
                ('country', models.CharField(blank=True, max_length=500)),
                ('zip_code', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Website_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=200)),
                ('primary_logo', models.ImageField(upload_to='logo')),
                ('secondary_logo', models.ImageField(upload_to='logo')),
                ('fev_icon', models.ImageField(upload_to='logo')),
                ('primary_background', models.ImageField(null=True, upload_to='background')),
                ('secondary_background', models.ImageField(null=True, upload_to='background')),
                ('short_description', models.CharField(max_length=500)),
            ],
        ),
    ]
