# Generated by Django 3.2.7 on 2021-10-07 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Website_Details',
            new_name='WebsiteDetails',
        ),
    ]
