# Generated by Django 3.2.7 on 2021-10-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0007_rename_gmap_link_address_gmap_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitedetails',
            name='secondary_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo'),
        ),
    ]
