# Generated by Django 3.2.7 on 2021-10-07 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0009_alter_websitedetails_fev_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FAQ_Branch', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FAQsSubSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField(max_length=500)),
                ('faqs', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='site_details.faqs')),
            ],
        ),
    ]
