# Generated by Django 3.2.7 on 2021-10-08 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0010_faqs_faqssubsection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FAQs',
            new_name='FAQ',
        ),
        migrations.RenameModel(
            old_name='WebsiteDetails',
            new_name='WebsiteDetail',
        ),
    ]
