# Generated by Django 3.2.7 on 2021-10-08 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0011_auto_20211008_2356'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FAQsSubSection',
            new_name='FAQ_Sub_Section',
        ),
    ]
