# Generated by Django 3.2.7 on 2021-10-08 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0012_rename_faqssubsection_faq_sub_section'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FAQ_Sub_Section',
            new_name='FaqSubSection',
        ),
    ]
