# Generated by Django 3.2.7 on 2021-11-29 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_details', '0013_rename_faq_sub_section_faqsubsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='site',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs_source', to='site_details.websitedetail'),
        ),
        migrations.AlterField(
            model_name='address',
            name='site',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='address_source', to='site_details.websitedetail'),
        ),
        migrations.AlterField(
            model_name='explainations',
            name='site',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='explainations_source', to='site_details.websitedetail'),
        ),
        migrations.AlterField(
            model_name='faqsubsection',
            name='faqs',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='faq_sub_section', to='site_details.faq'),
        ),
        migrations.AlterField(
            model_name='partnerprogram',
            name='site',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='partnerprogram_source', to='site_details.websitedetail'),
        ),
    ]
