# Generated by Django 3.2.7 on 2021-10-01 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210927_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreview',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_review', to='products.product'),
        ),
    ]
