# Generated by Django 3.2.7 on 2021-10-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_offer_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer_percent',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
