# Generated by Django 3.2.7 on 2021-10-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_offer_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreview',
            name='created_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='customerreview',
            name='updated_on',
            field=models.DateTimeField(null=True),
        ),
    ]
