# Generated by Django 3.2.7 on 2021-10-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20211007_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreview',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerreview',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
