# Generated by Django 3.2.7 on 2021-10-06 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20211007_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productssubcategory',
            name='base_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcat', to='products.productscategory'),
        ),
    ]
