# Generated by Django 3.2.7 on 2021-10-08 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_productssubcategory_base_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductsCategory',
            new_name='ProductCategory',
        ),
        migrations.RenameModel(
            old_name='ProductsSubCategory',
            new_name='ProductSubCategory',
        ),
    ]
