# Generated by Django 3.2.7 on 2021-10-08 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='root_user',
            new_name='user',
        ),
    ]
