# Generated by Django 3.2.7 on 2021-10-08 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_catalog', '0002_rename_root_user_seller_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='shop_name',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.CreateModel(
            name='ShopProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_logo', models.ImageField(upload_to='logo')),
                ('primary_background', models.ImageField(null=True, upload_to='vendor/background')),
                ('short_description', models.TextField(max_length=200, null=True)),
                ('shop_owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop_root', to='vendor_catalog.seller')),
            ],
        ),
    ]
