# Generated by Django 3.2.7 on 2021-10-08 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_catalog', '0003_auto_20211008_2321'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopProfile',
            new_name='ShopInfo',
        ),
    ]
