# Generated by Django 3.2.7 on 2021-11-30 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_catalog', '0004_rename_shopprofile_shopinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopinfo',
            name='shop_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_root', to='vendor_catalog.seller'),
        ),
    ]
