# Generated by Django 3.2.7 on 2021-10-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featured_products', '0002_alter_featuredproducts_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredproducts',
            name='type',
            field=models.CharField(blank=True, choices=[('slider', 'Slider'), ('featured', 'Featured'), ('categories_menu', 'Categories Menu'), ('specialdiscount', 'Special Discount')], max_length=100, null=True),
        ),
    ]
