# Generated by Django 3.2.7 on 2021-10-02 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('featured_products', '0003_alter_featuredproducts_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featuredproducts',
            old_name='product',
            new_name='Select_Product',
        ),
    ]
