# Generated by Django 3.2.7 on 2021-10-03 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_offer_percent'),
        ('featured_products', '0005_alter_featuredproducts_select_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeaturedProducts',
            new_name='PromotionalProducts',
        ),
    ]
