# Generated by Django 3.2.7 on 2021-10-08 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20211009_0009'),
        ('featured_products', '0006_rename_featuredproducts_promotionalproducts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PromotionalProducts',
            new_name='PromotionalProduct',
        ),
    ]
